-- Live-safe PostgreSQL SQL for the extended profile fields.
-- The Laravel migration uses Schema::hasColumn() guards; this file is for
-- operators who prefer to apply the same additive changes manually.

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS business_logo_id UUID NULL,
    ADD COLUMN IF NOT EXISTS state VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS country VARCHAR(100) NULL DEFAULT 'India',
    ADD COLUMN IF NOT EXISTS preferred_language VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS business_category_id UUID NULL,
    ADD COLUMN IF NOT EXISTS business_sub_category VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS company_type VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS year_of_establishment INTEGER NULL,
    ADD COLUMN IF NOT EXISTS annual_revenue_range VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS number_of_employees VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS gst_number VARCHAR(30) NULL,
    ADD COLUMN IF NOT EXISTS business_website VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS superpower VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS i_can_help_with JSONB NULL,
    ADD COLUMN IF NOT EXISTS i_am_looking_for JSONB NULL,
    ADD COLUMN IF NOT EXISTS business_keywords JSONB NULL,
    ADD COLUMN IF NOT EXISTS products_services_offered TEXT NULL,
    ADD COLUMN IF NOT EXISTS secondary_mobile VARCHAR(30) NULL,
    ADD COLUMN IF NOT EXISTS linkedin_profile VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS instagram_handle VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS twitter_handle VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS facebook_profile VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS youtube_channel VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS other_website VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS contact_visibility VARCHAR(50) NULL DEFAULT 'connections',
    ADD COLUMN IF NOT EXISTS business_address TEXT NULL,
    ADD COLUMN IF NOT EXISTS business_city VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS business_state VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS business_pincode VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS business_country VARCHAR(100) NULL DEFAULT 'India',
    ADD COLUMN IF NOT EXISTS google_maps_latitude DECIMAL(10,7) NULL,
    ADD COLUMN IF NOT EXISTS google_maps_longitude DECIMAL(10,7) NULL,
    ADD COLUMN IF NOT EXISTS industries_of_interest JSONB NULL,
    ADD COLUMN IF NOT EXISTS collaboration_goals JSONB NULL,
    ADD COLUMN IF NOT EXISTS preferred_meeting_format VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS willing_to_mentor BOOLEAN NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS open_to_cross_city_collaboration BOOLEAN NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS open_to_speaking_at_events BOOLEAN NULL DEFAULT false;
