@extends('admin.layouts.app')
@section('title', 'Greenpreneur App Config')
@php
$active = request('tab','overview');
$tabs = ['overview'=>'Overview','branding'=>'Branding','labels'=>'Labels','features'=>'Features','navigation'=>'Navigation','widgets'=>'Dashboard Widgets','social'=>'Social Links','membership'=>'Membership Labels','api-docs'=>'API Docs'];
$branding = (array) ($branding ?? []);
$colorFields = ['primary_color','secondary_color','accent_color','splash_bg_color','button_color','text_color'];
$brandFields = ['app_name','app_logo_url','splash_logo_url','primary_color','secondary_color','accent_color','splash_bg_color','button_color','text_color','playstore_url','appstore_url','website_url','support_email','support_phone'];
$menuTypes = ['bottom_nav','plus_menu','impact_menu','drawer'];
$docs = [
['GET','/app/config','No','Public Flutter app config','{}','{"success":true,"data":{"app_info":{},"labels":{}}}'],
['GET','/admin/app-config','Yes','Fetch full admin config','{}','{"success":true,"data":{"branding":{},"labels":[]}}'],
['PUT','/admin/app-config/branding','Yes','Update branding','{"app_name":"Greenpreneur"}','{"success":true}'],
['PUT','/admin/app-config/labels/{label_key}','Yes','Update one label','{"label_value":"Green Member"}','{"success":true}'],
['PUT','/admin/app-config/labels','Yes','Bulk update labels','{"labels":{"peer":"Green Member"}}','{"success":true}'],
['PUT','/admin/app-config/features/{feature_key}','Yes','Update one feature','{"is_enabled":true}','{"success":true}'],
['PUT','/admin/app-config/features','Yes','Bulk update features','{"features":{"events":true}}','{"success":true}'],
['POST','/admin/app-config/navigation','Yes','Create navigation item','{"menu_type":"bottom_nav","item_key":"feed"}','{"success":true}'],
['PUT','/admin/app-config/navigation/{id}','Yes','Update navigation item','{"display_label":"Feed"}','{"success":true}'],
['DELETE','/admin/app-config/navigation/{id}','Yes','Delete navigation item','{}','{"success":true}'],
['PUT','/admin/app-config/dashboard-widgets/{widget_key}','Yes','Update dashboard widget','{"is_enabled":true}','{"success":true}'],
['PUT','/admin/app-config/social-links/{platform}','Yes','Update social link','{"display_name":"LinkedIn","url":"https://linkedin.com/company/greenpreneur"}','{"success":true}'],
['POST','/admin/app-config/clear-cache','Yes','Clear app config cache','{}','{"success":true}'],
];
@endphp
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3">
    <div><h1 class="h4 mb-1">Greenpreneur App Config</h1><div class="text-muted small">Manage branding, labels, menus, widgets, membership labels, and social links for the greenpreneur app instance.</div></div>
    <form method="POST" action="{{ route('admin.app-config.clear-cache') }}">@csrf <input type="hidden" name="tab" value="{{ $active }}"><button class="btn btn-outline-success btn-sm"><i class="bi bi-arrow-clockwise me-1"></i>Clear App Config Cache</button></form>
</div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<ul class="nav nav-pills flex-wrap gap-1 mb-3">@foreach($tabs as $key=>$label)<li class="nav-item"><a class="nav-link {{ $active===$key?'active':'' }}" href="?tab={{ $key }}">{{ $label }}</a></li>@endforeach</ul>
<div class="tab-content">
@if($active==='overview')
<div class="row g-3 mb-3">
@foreach(['App Name'=>$branding['app_name'] ?? 'Greenpreneur','App Slug'=>$app->slug,'Total Labels'=>$labels->count(),'Enabled Features'=>$features->where('is_enabled',true)->count(),'Disabled Features'=>$features->where('is_enabled',false)->count(),'Navigation Items Count'=>$navigation->count(),'Enabled Dashboard Widgets'=>$widgets->filter(fn($w)=>($w->is_enabled ?? $w->is_enable ?? false))->count(),'Social Links Count'=>$socialLinks->count(),'Last Updated'=>$lastUpdated ?: '—'] as $k=>$v)
<div class="col-sm-6 col-lg-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-muted small">{{ $k }}</div><div class="fs-5 fw-semibold">{{ $v }}</div></div></div></div>
@endforeach
</div><div class="card"><div class="card-body"><div class="fw-semibold mb-2">Public Flutter API</div><code>GET https://peersunity.com/api/v1/app/config</code><a href="https://peersunity.com/api/v1/app/config" target="_blank" class="btn btn-sm btn-success ms-2">Test Public Config API</a></div></div>
@endif
@if($active==='branding')
<form method="POST" action="{{ route('admin.app-config.branding') }}" class="card shadow-sm"><div class="card-body row g-3">@csrf @method('PUT')
@foreach($brandFields as $field)<div class="col-md-6"><label class="form-label">{{ $field }}</label><div class="input-group">@if(in_array($field,$colorFields,true))<input type="color" class="form-control form-control-color" value="{{ $branding[$field] ?? '#198754' }}" onchange="this.nextElementSibling.value=this.value">@endif<input name="{{ $field }}" value="{{ old($field, $branding[$field] ?? ($field==='app_name'?'Greenpreneur':'')) }}" class="form-control" placeholder="{{ $field }}"></div></div>@endforeach
</div><div class="card-footer"><button class="btn btn-success">Save Branding</button></div></form>
@endif
@if($active==='labels')
<form method="POST" action="{{ route('admin.app-config.labels') }}" class="card shadow-sm">@csrf @method('PUT')<div class="card-body"><input class="form-control form-control-sm mb-3 js-search" data-target="#labelsTable" placeholder="Search labels"><div class="table-responsive"><table id="labelsTable" class="table table-sm table-bordered align-middle"><thead class="table-light"><tr><th>Label Key</th><th>Label Value</th><th>Group Name</th><th>Description</th><th>Active</th><th>Action</th></tr></thead><tbody>@foreach($labels as $l)<tr><td><code>{{ $l->label_key }}</code></td><td><input class="form-control form-control-sm" name="labels[{{ $l->label_key }}][label_value]" value="{{ $l->label_value }}"></td><td><input class="form-control form-control-sm" name="labels[{{ $l->label_key }}][group_name]" value="{{ $l->group_name }}"></td><td><input class="form-control form-control-sm" name="labels[{{ $l->label_key }}][description]" value="{{ $l->description }}"></td><td><input type="checkbox" class="form-check-input" name="labels[{{ $l->label_key }}][is_active]" value="1" @checked($l->is_active)></td><td><button class="btn btn-sm btn-outline-success">Save</button></td></tr>@endforeach</tbody></table></div></div><div class="card-footer"><button class="btn btn-success">Bulk Save Labels</button></div></form>
@endif
@if($active==='features')
<form method="POST" action="{{ route('admin.app-config.features') }}" class="card shadow-sm">@csrf @method('PUT')<div class="card-body"><input class="form-control form-control-sm mb-3 js-search" data-target="#featuresTable" placeholder="Search features"><div class="table-responsive"><table id="featuresTable" class="table table-sm table-bordered align-middle"><thead class="table-light"><tr><th>Feature Key</th><th>Feature Name</th><th>Status Toggle</th><th>Sort Order</th><th>Action</th></tr></thead><tbody>@foreach($features as $f)<tr><td><code>{{ $f->feature_key }}</code></td><td>{{ $f->feature_name }}</td><td><span class="badge {{ $f->is_enabled?'bg-success':'bg-danger' }}">{{ $f->is_enabled?'Enabled':'Disabled' }}</span> <input type="checkbox" class="form-check-input ms-2" name="features[{{ $f->feature_key }}][is_enabled]" value="1" @checked($f->is_enabled)></td><td><input type="number" min="0" class="form-control form-control-sm" name="features[{{ $f->feature_key }}][sort_order]" value="{{ $f->sort_order }}"></td><td><button class="btn btn-sm btn-outline-success">Save</button></td></tr>@endforeach</tbody></table></div></div><div class="card-footer"><button class="btn btn-success">Bulk Save Features</button></div></form>
@endif
@if($active==='navigation')
<div class="card mb-3"><div class="card-body"><form method="POST" action="{{ route('admin.app-config.navigation.store') }}" class="row g-2">@csrf @foreach(['item_key','label_key','display_label','icon','route_name','feature_key'] as $f)<div class="col-md-2"><input name="{{ $f }}" class="form-control form-control-sm" placeholder="{{ $f }}" @if($f==='display_label'||$f==='item_key') required @endif></div>@endforeach<div class="col-md-2"><select name="menu_type" class="form-select form-select-sm">@foreach($menuTypes as $m)<option>{{ $m }}</option>@endforeach</select></div><div class="col-md-1"><input name="sort_order" type="number" value="0" class="form-control form-control-sm"></div><div class="col-md-1 form-check"><input name="is_enabled" value="1" checked type="checkbox" class="form-check-input"><label class="small">On</label></div><div class="col-md-1"><button class="btn btn-sm btn-success">Add</button></div></form></div></div>
@foreach($menuTypes as $menu)<div class="card shadow-sm mb-3"><div class="card-header fw-semibold">{{ $menu }}</div><div class="table-responsive"><table class="table table-sm table-bordered align-middle mb-0"><thead class="table-light"><tr><th>Sort</th><th>Item Key</th><th>Display Label</th><th>Icon</th><th>Route</th><th>Feature</th><th>Enabled</th><th>Actions</th></tr></thead><tbody>@foreach($navigation->where('menu_type',$menu) as $n)<tr><form method="POST" action="{{ route('admin.app-config.navigation.update',$n->id) }}">@csrf @method('PUT')<input type="hidden" name="menu_type" value="{{ $menu }}"><td><input name="sort_order" value="{{ $n->sort_order }}" class="form-control form-control-sm" type="number"></td><td><input name="item_key" value="{{ $n->item_key }}" class="form-control form-control-sm"></td><td><input name="display_label" value="{{ $n->display_label }}" class="form-control form-control-sm"><input type="hidden" name="label_key" value="{{ $n->label_key }}"></td><td><input name="icon" value="{{ $n->icon }}" class="form-control form-control-sm"></td><td><input name="route_name" value="{{ $n->route_name }}" class="form-control form-control-sm"></td><td><input name="feature_key" value="{{ $n->feature_key }}" class="form-control form-control-sm"></td><td><input type="checkbox" name="is_enabled" value="1" @checked($n->is_enabled)></td><td><button class="btn btn-sm btn-outline-success">Save</button></form><form method="POST" class="d-inline" action="{{ route('admin.app-config.navigation.destroy',$n->id) }}" onsubmit="return confirm('Delete this navigation item?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>@endforeach</tbody></table></div></div>@endforeach
@endif
@if($active==='widgets')
<form method="POST" action="{{ route('admin.app-config.widgets') }}" class="card shadow-sm">@csrf @method('PUT')<div class="table-responsive"><table class="table table-sm table-bordered align-middle mb-0"><thead class="table-light"><tr><th>Widget Key</th><th>Widget Name</th><th>Enabled</th><th>Sort Order</th><th>Action</th></tr></thead><tbody>@foreach($widgets as $w)<tr><td><code>{{ $w->widget_key }}</code></td><td>{{ $w->widget_name }}</td><td><input type="checkbox" name="widgets[{{ $w->widget_key }}][is_enabled]" value="1" @checked($w->is_enabled ?? $w->is_enable ?? false)></td><td><input type="number" min="0" class="form-control form-control-sm" name="widgets[{{ $w->widget_key }}][sort_order]" value="{{ $w->sort_order }}"></td><td><button class="btn btn-sm btn-outline-success">Save</button></td></tr>@endforeach</tbody></table></div><div class="card-footer"><button class="btn btn-success">Save Widgets</button></div></form>
@endif
@if($active==='social')
<form method="POST" action="{{ route('admin.app-config.social') }}" class="card shadow-sm">@csrf @method('PUT')<div class="table-responsive"><table class="table table-sm table-bordered align-middle mb-0"><thead class="table-light"><tr><th>Platform</th><th>Display Name</th><th>URL</th><th>Icon</th><th>Enabled</th><th>Sort Order</th><th>Action</th></tr></thead><tbody>@foreach($socialLinks as $s)<tr><td><code>{{ $s->platform }}</code></td><td><input class="form-control form-control-sm" name="social_links[{{ $s->platform }}][display_name]" value="{{ $s->display_name }}"></td><td><input class="form-control form-control-sm" name="social_links[{{ $s->platform }}][url]" value="{{ $s->url }}" placeholder="nullable"></td><td><input class="form-control form-control-sm" name="social_links[{{ $s->platform }}][icon]" value="{{ $s->icon }}"></td><td><input type="checkbox" name="social_links[{{ $s->platform }}][is_enabled]" value="1" @checked($s->is_enabled)></td><td><input type="number" class="form-control form-control-sm" name="social_links[{{ $s->platform }}][sort_order]" value="{{ $s->sort_order }}"></td><td><button class="btn btn-sm btn-outline-success">Save</button></td></tr>@endforeach</tbody></table></div><div class="card-footer"><button class="btn btn-success">Save Social Links</button></div></form>
@endif
@if($active==='membership')
<form method="POST" action="{{ route('admin.app-config.membership-labels') }}" class="card shadow-sm">@csrf @method('PUT')<div class="table-responsive"><table class="table table-sm table-bordered align-middle mb-0"><thead class="table-light"><tr><th>Membership Key</th><th>Display Label</th><th>Description</th><th>Action</th></tr></thead><tbody>@foreach($membershipLabels as $m)<tr><td><code>{{ $m->membership_key }}</code></td><td><input class="form-control form-control-sm" name="membership_labels[{{ $m->membership_key }}][display_label]" value="{{ $m->display_label }}"></td><td><input class="form-control form-control-sm" name="membership_labels[{{ $m->membership_key }}][description]" value="{{ $m->description }}"></td><td><button class="btn btn-sm btn-outline-success">Save</button></td></tr>@endforeach</tbody></table></div><div class="card-footer"><button class="btn btn-success">Save Membership Labels</button></div></form>
@endif
@if($active==='api-docs')
<div class="card shadow-sm"><div class="card-body"><p><strong>Base URL:</strong> <code>https://peersunity.com/api/v1</code></p><p><strong>Admin headers:</strong> <button class="btn btn-sm btn-outline-secondary copy-btn" data-copy="Authorization: Bearer ADMIN_TOKEN\nAccept: application/json\nContent-Type: application/json">Copy Headers</button></p><div class="table-responsive"><table class="table table-sm table-bordered align-middle"><thead class="table-light"><tr><th>Method</th><th>Endpoint</th><th>Auth Required</th><th>Purpose</th><th>Request Body Example</th><th>Response Example</th><th>Copy</th></tr></thead><tbody>@foreach($docs as $d)<tr><td><span class="badge bg-primary">{{ $d[0] }}</span></td><td><code>{{ $d[1] }}</code></td><td>{{ $d[2] }}</td><td>{{ $d[3] }}</td><td><pre class="small mb-0">{{ $d[4] }}</pre></td><td><pre class="small mb-0">{{ $d[5] }}</pre></td><td><button class="btn btn-sm btn-outline-secondary copy-btn" data-copy="{{ $d[1] }}">Endpoint</button><button class="btn btn-sm btn-outline-secondary copy-btn" data-copy="{{ $d[4] }}">JSON</button></td></tr>@endforeach</tbody></table></div></div></div>
@endif
</div>
@endsection
@push('scripts')<script>document.querySelectorAll('.js-search').forEach(i=>i.addEventListener('input',()=>{document.querySelectorAll(i.dataset.target+' tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(i.value.toLowerCase())?'':'none')}));document.querySelectorAll('.copy-btn').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();navigator.clipboard.writeText(b.dataset.copy||'');b.textContent='Copied';setTimeout(()=>b.textContent='Copy',1200)}));</script>@endpush
